packages:
  - "apps/*"

overrides:
  zeptomatch: "1.2.0"
  "@hono/node-server@<1.19.13": ">=1.19.13"

allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
